export const events = [
  {
    title: "React Summit Amsterdam",
    slug: "react-summit-amsterdam",
    image: "/images/event1.png",
    location: "Amsterdam, Netherlands",
    date: "June 12-13, 2026",
    time: "9:00 AM - 6:00 PM",
  },
  {
    title: "KubeCon + CloudNativeCon Europe",
    slug: "kubecon-cloudnativecon-europe",
    image: "/images/event2.png",
    location: "Amsterdam, Netherlands",
    date: "March 23-26, 2026",
    time: "8:00 AM - 5:00 PM",
  },
  {
    title: "GitHub Universe",
    slug: "github-universe",
    image: "/images/event3.png",
    location: "San Francisco, CA",
    date: "October 28-29, 2026",
    time: "9:00 AM - 5:00 PM",
  },
  {
    title: "JSConf EU",
    slug: "jsconf-eu",
    image: "/images/event4.png",
    location: "Berlin, Germany",
    date: "September 10-11, 2026",
    time: "9:00 AM - 6:00 PM",
  },
  {
    title: "HackMIT",
    slug: "hackmit",
    image: "/images/event5.png",
    location: "Cambridge, MA",
    date: "September 19-20, 2026",
    time: "10:00 AM - 10:00 AM",
  },
  {
    title: "PyCon US",
    slug: "pycon-us",
    image: "/images/event6.png",
    location: "Long Beach, CA",
    date: "May 13-21, 2026",
    time: "8:00 AM - 6:00 PM",
  },
  {
    title: "Google I/O",
    slug: "google-io",
    image: "/images/event-full.png",
    location: "Mountain View, CA",
    date: "May 19-20, 2026",
    time: "9:00 AM - 5:00 PM",
  },
] as const;
